Fix detection of msmpi

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -14,7 +14,7 @@ jobs:
     runs-on: ${{ matrix.os }}
     env:
       VCPKG_DISABLE_METRICS: 1
-      VCPKG_DEPS_JSON: ${{ github.workspace }}/.github/vcpkg.json
+      VCPKG_DEPS_JSON: .github/vcpkg.json
 
     steps:
       - name: Checkout source code
@@ -42,13 +42,12 @@ jobs:
         id: check-msmpi
         shell: bash
         run: |
-          $VCPKG_INSTALLATION_ROOT/vcpkg list msmpi:x64-windows
-          exit 1
-          isinstalled=$( $VCPKG_INSTALLATION_ROOT/vcpkg list msmpi:x64-windows | wc -l )
-          echo "::set-output name=msmpi::$isinstalled"
+          # When no package is installed, "vcpkg list msmpi" prints a line
+          missing=$( VCPKG_INSTALLATION_ROOT/vcpkg list msmpi | grep -q msmpi; echo $? )
+          echo "::set-output name=missing::$missing"
 
       - name: Downloading MPI
-        if: steps.check-msmpi.outputs.msmpi == 0
+        if: steps.check-msmpi.outputs.missing == 1
         # URLs copied from https://github.com/microsoft/vcpkg/blob/master/ports/msmpi/portfile.cmake
         shell: powershell
         run: |
@@ -57,7 +56,7 @@ jobs:
             $client.DownloadFile("https://download.microsoft.com/download/a/5/2/a5207ca5-1203-491a-8fb8-906fd68ae623/msmpisdk.msi", "msmpisdk.msi")
 
       - name: Installing MPI
-        if: steps.check-msmpi.outputs.msmpi == 0
+        if: steps.check-msmpi.outputs.missing == 1
         shell: cmd
         run: |
             msmpisetup.exe -unattend
@@ -66,5 +65,4 @@ jobs:
       - name: Install vcpkg packages
         shell: bash
         run: |
-          $VCPKG_INSTALLATION_ROOT/vcpkg install --debug --triplet x64-windows $(jq -j '.dependencies[] | ., " "' $(echo -E '${{ env.VCPKG_DEPS_JSON }}' | sed -e 's,\\,/,g'))
-
+          $VCPKG_INSTALLATION_ROOT/vcpkg install --debug --triplet x64-windows $(jq -j '.dependencies[] | ., " "' $VCPKG_DEPS_JSON)
